// --- NAMESPACE: The folder address where this file lives inside the project ---
namespace TaskManager.Domain.Entities;

/// <summary>
/// Domain Entity: Represents the core 'Task' object in our system.
/// This file holds the data and the core business rules for a single task.
/// </summary>
public class TaskItem
{
    // 1. UNIQUE IDENTIFIER: The unique ID number generated by the database (e.g., 1, 2, 3)
    public int Id { get; set; }

    // 2. TITLE: The name of the task. Defaults to an empty string to avoid null crashes.
    public string Title { get; set; } = string.Empty;

    // 3. DESCRIPTION: Detailed notes about the task. Defaults to empty string.
    public string Description { get; set; } = string.Empty;

    // 4. STATUS: True if the task is finished, false if it is still open.
    public bool IsCompleted { get; set; }

    // 5. CREATION DATE: Records the exact date and time this task was created.
    public DateTime CreatedAt { get; set; }

    // 6. COMPLETION DATE: The date/time it was finished. 
    // The '?' means it can be NULL (empty) if the task isn't completed yet.
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// BUSINESS RULE #1: Logic to mark a task as complete.
    /// Protects the entity from being completed twice.
    /// </summary>
    public void MarkComplete()
    {
        // Check if the task is already completed
        if (IsCompleted)
        {
            // Throw an exception to stop invalid operations
            throw new InvalidOperationException("Task is already completed.");
        }

        // Update the properties correctly
        IsCompleted = true;
        CompletedAt = DateTime.UtcNow; // Stamp current UTC time
    }

    /// <summary>
    /// BUSINESS RULE #2: Logic to reopen a completed task.
    /// </summary>
    public void Reopen()
    {
        // Check if the task is NOT completed
        if (!IsCompleted)
        {
            // Can't reopen a task that is already open
            throw new InvalidOperationException("Task is not completed.");
        }

        // Reset the properties
        IsCompleted = false;
        CompletedAt = null; // Clear out the completed date
    }
}